# -*- coding: utf-8 -*-

countries = [
	{"name": "AFGHANISTAN", "code": "AF"},
	{"name": "ÅLAND ISLANDS", "code": "AX"},
	{"name": "ALBANIA", "code": "AL"},
	{"name": "ALGERIA", "code": "DZ"},
	{"name": "AMERICAN SAMOA", "code": "AS"},
	{"name": "ANDORRA", "code": "AD"},
	{"name": "ANGOLA", "code": "AO"},
	{"name": "ANGUILLA", "code": "AI"},
	{"name": "ANTARCTICA", "code": "AQ"},
	{"name": "ANTIGUA AND BARBUDA", "code": "AG"},
	{"name": "ARGENTINA", "code": "AR"},
	{"name": "ARMENIA", "code": "AM"},
	{"name": "ARSSR", "translation": "ARMENIA"},
	{"name": "ARUBA", "code": "AW"},
	{"name": "AUSTRALIA", "code": "AU"},
	{"name": "AUSTRIA", "code": "AT"},
	{"name": "AZERBAIJAN", "code": "AZ"},
	{"name": "AZSSR", "translation": "AZERBAIJAN"},
	{"name": "BAHAMAS", "code": "BS"},
	{"name": "BAHRAIN", "code": "BH"},
	{"name": "BANGLADESH", "code": "BD"},
	{"name": "BARBADOS", "code": "BB"},
	{"name": "BYELARUS", "translation": "BELARUS"},
	{"name": "BREST STATE", "translation": "BELARUS"},
	{"name": "BELARUS", "code": "BY"},
	{"name": "BELGIUM", "code": "BE"},
	{"name": "BELIZE", "code": "BZ"},
	{"name": "BENIN", "code": "BJ"},
	{"name": "BERMUDA", "code": "BM"},
	{"name": "BHUTAN", "code": "BT"},
	{"name": "BOLIVIA", "code": "BO"},
	{"name": "BOSNIA AND HERZEGOVINA", "code": "BA"},
	{"name": "BOSNIA \& HERCEG", "translation": "BOSNIA AND HERZEGOVINA"},
	{"name": "BOTSWANA", "code": "BW"},
	{"name": "BOUVET ISLAND", "code": "BV"},
	{"name": "BRAZIL", "code": "BR"},
	{"name": "VALONGO, JANERO", "translation": "BRAZIL"},
	{"name": "BRASIL", "translation": "BRAZIL"},
	{"name": "BRITISH INDIAN OCEAN TERRITORY", "code": "IO"},
	{"name": "BRUNEI DARUSSALAM", "code": "BN"},
	{"name": "BULGARIA", "code": "BG"},
	{"name": "BURKINA FASO", "code": "BF"},
	{"name": "BURUNDI", "code": "BI"},
	{"name": "CAMBODIA", "code": "KH"},
	{"name": "CAMEROON", "code": "CM"},
	{"name": "CANADA", "code": "CA"},
	{"name": "CAPE VERDE", "code": "CV"},
	{"name": "CAYMAN ISLANDS", "code": "KY"},
	{"name": "CENTRAL AFRICAN REPUBLIC", "code": "CF"},
	{"name": "CHAD", "code": "TD"},
	{"name": "CHILE", "code": "CL"},
	{"name": "CHINA", "code": "CN"},
	{"name": "CHRISTMAS ISLAND", "code": "CX"},
	{"name": "COCOS (KEELING) ISLANDS", "code": "CC"},
	{"name": "COLOMBIA", "code": "CO"},
	{"name": "COMOROS", "code": "KM"},
	{"name": "CONGO", "code": "CG"},
	{"name": "CONGO, THE DEMOCRATIC REPUBLIC OF THE", "code": "CD"},
	{"name": "COOK ISLANDS", "code": "CK"},
	{"name": "COSTA RICA", "code": "CR"},
	{"name": "COTE D'IVOIRE", "code": "CI"},
	{"name": "CROATIA", "code": "HR"},
	{"name": "CUBA", "code": "CU"},
	{"name": "CYPRUS", "code": "CY"},
	{"name": "CZECH REPUBLIC", "code": "CZ"},
	{"name": "DENMARK", "code": "DK"},
	{"name": "DJIBOUTI", "code": "DJ"},
	{"name": "DOMINICA", "code": "DM"},
	{"name": "DOMINICAN REPUBLIC", "code": "DO"},
	{"name": "ECUADOR", "code": "EC"},
	{"name": "EGYPT", "code": "EG"},
	{"name": "EL SALVADOR", "code": "SV"},
	{"name": "EQUATORIAL GUINEA", "code": "GQ"},
	{"name": "ERITREA", "code": "ER"},
	{"name": "ESTONIA", "code": "EE"},
	{"name": "ETHIOPIA", "code": "ET"},
	{"name": "FALKLAND ISLANDS (MALVINAS)", "code": "FK"},
	{"name": "FAROE ISLANDS", "code": "FO"},
	{"name": "FIJI", "code": "FJ"},
	{"name": "FINLAND", "code": "FI"},
	{"name": "FRANCE", "code": "FR"},
	{"name": "FRENCH GUIANA", "code": "GF"},
	{"name": "FRENCH POLYNESIA", "code": "PF"},
	{"name": "FR POLYNESIA", "translation": "FRENCH POLYNESIA"},
	{"name": "FRENCH SOUTHERN TERRITORIES", "code": "TF"},
	{"name": "GABON", "code": "GA"},
	{"name": "GAMBIA", "code": "GM"},
	{"name": "GEORGIA", "code": "GE"},
	{"name": "ABASTUMANI,GESSR", "translation": "GEORGIA"},
	{"name": "GERMANY", "code": "DE"},
	{"name": "BUNDES REPUBLIK", "translation": "GERMANY"},
	{"name": "FED REP GER", "translation": "GERMANY"},
	{"name": "GER DEM REP", "translation": "GERMANY"},
	{"name": "GHANA", "code": "GH"},
	{"name": "GIBRALTAR", "code": "GI"},
	{"name": "GREECE", "code": "GR"},
	{"name": "GREENLAND", "code": "GL"},
	{"name": "GRENADA", "code": "GD"},
	{"name": "GUADELOUPE", "code": "GP"},
	{"name": "GUAM", "code": "GU"},
	{"name": "GUATEMALA", "code": "GT"},
	{"name": "GUERNSEY", "code": "GG"},
	{"name": "GUINEA", "code": "GN"},
	{"name": "VIETNAM"},
	{"name": "GUINEA-BISSAU", "code": "GW"},
	{"name": "GUYANA", "code": "GY"},
	{"name": "HAITI", "code": "HT"},
	{"name": "HEARD ISLAND AND MCDONALD ISLANDS", "code": "HM"},
	{"name": "HOLY SEE (VATICAN CITY STATE)", "code": "VA"},
	{"name": "VATICAN", "code": "VA", "translation": "HOLY SEE (VATICAN CITY STATE)"},
	{"name": "HONDURAS", "code": "HN"},
	{"name": "HONG KONG", "code": "HK"},
	{"name": "HUNGARY", "code": "HU"},
	{"name": "ICELAND", "code": "IS"},
	{"name": "INDIA", "code": "IN"},
	{"name": "INDONESIA", "code": "ID"},
	{"name": "IRAN, ISLAMIC REPUBLIC OF", "code": "IR"},
	{"name": "IRAN", "translation": "IRAN, ISLAMIC REPUBLIC OF"},
	{"name": "IRAQ", "code": "IQ"},
	{"name": "IRELAND", "code": "IE"},
	{"name": "ISLE OF MAN", "code": "IM"},
	{"name": "ISRAEL", "code": "IL"},
	{"name": "ITALY", "code": "IT"},
	{"name": "ITALIA", "translation": "ITALY"},
	{"name": "JAMAICA", "code": "JM"},
	{"name": "JAPAN", "code": "JP"},
	{"name": "JERSEY", "code": "JE"},
	{"name": "JORDAN", "code": "JO"},
	{"name": "KAZAKHSTAN", "code": "KZ"},
	{"name": "KENYA", "code": "KE"},
	{"name": "KIRIBATI", "code": "KI"},
	{"name": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "translation": "NORTH KOREA"},
	{"name": "NORTH KOREA", "code": "KP"},
	{"name": "KOREA, REPUBLIC OF", "translation": "SOUTH KOREA"},
	{"name": "SOUTH KOREA", "code": "KR"},
	{"name": "KUWAIT", "code": "KW"},
	{"name": "KYRGYZSTAN", "code": "KG"},
	{"name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "code": "LA"},
	{"name": "LATVIA", "code": "LV"},
	{"name": "LEBANON", "code": "LB"},
	{"name": "LESOTHO", "code": "LS"},
	{"name": "LIBERIA", "code": "LR"},
	{"name": "LIBYAN ARAB JAMAHIRIYA", "translation": "LIBYA"},
	{"name": "LIBYA", "code": "LY"},
	{"name": "LIECHTENSTEIN", "code": "LI"},
	{"name": "LITHUANIA", "code": "LT"},
	{"name": "LUXEMBOURG", "code": "LU"},
	{"name": "MACAO", "code": "MO"},
	{"name": "YUGOSLAVIA", "translation": "MACEDONIA"},
	{"name": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "translation": "MACEDONIA"},
	{"name": "MACEDONIA", "code": "MK"},
	{"name": "MADAGASCAR", "code": "MG"},
	{"name": "MALAWI", "code": "MW"},
	{"name": "MALAYSIA", "code": "MY"},
	{"name": "MALDIVES", "code": "MV"},
	{"name": "MALI", "code": "ML"},
	{"name": "MALTA", "code": "MT"},
	{"name": "MARSHALL ISLANDS", "code": "MH"},
	{"name": "MARTINIQUE", "code": "MQ"},
	{"name": "MAURITANIA", "code": "MR"},
	{"name": "MAURITIUS", "code": "MU"},
	{"name": "MAYOTTE", "code": "YT"},
	{"name": "MEXICO", "code": "MX"},
	{"name": "MICRONESIA, FEDERATED STATES OF", "code": "FM"},
	{"name": "MOLDOVA, REPUBLIC OF", "code": "MD"},
	{"name": "MOLDOVA", "translation": "MOLDOVA, REPUBLIC OF"},
	{"name": "MONACO", "code": "MC"},
	{"name": "MONGOLIA", "code": "MN"},
	{"name": "MONGOL PEO REP", "translation": "MONGOLIA"},
	{"name": "MONTSERRAT", "code": "MS"},
	{"name": "MOROCCO", "code": "MA"},
	{"name": "MOZAMBIQUE", "code": "MZ"},
	{"name": "MYANMAR", "code": "MM"},
	{"name": "NAMIBIA", "code": "NA"},
	{"name": "NAURU", "code": "NR"},
	{"name": "NEPAL", "code": "NP"},
	{"name": "NETHERLANDS", "code": "NL"},
	{"name": "NETHERLANDS ANTILLES", "code": "AN"},
	{"name": "NEW CALEDONIA", "code": "NC"},
	{"name": "NEW ZEALAND", "code": "NZ"},
	{"name": "NICARAGUA", "code": "NI"},
	{"name": "NIGER", "code": "NE"},
	{"name": "NIGERIA", "code": "NG"},
	{"name": "NIUE", "code": "NU"},
	{"name": "NORFOLK ISLAND", "code": "NF"},
	{"name": "NORTHERN MARIANA ISLANDS", "code": "MP"},
	{"name": "NORWAY", "code": "NO"},
	{"name": "OMAN", "code": "OM"},
	{"name": "PAKISTAN", "code": "PK"},
	{"name": "PALAU", "code": "PW"},
	{"name": "PALESTINIAN TERRITORY, OCCUPIED", "code": "PS"},
	{"name": "PANAMA", "code": "PA"},
	{"name": "PAPUA NEW GUINEA", "code": "PG"},
	{"name": "PARAGUAY", "code": "PY"},
	{"name": "PERU", "code": "PE"},
	{"name": "PHILIPPINES", "code": "PH"},
	{"name": "PITCAIRN", "code": "PN"},
	{"name": "POLAND", "code": "PL"},
	{"name": "PORTUGAL", "code": "PT"},
	{"name": "PUERTO RICO", "code": "PR"},
	{"name": "QATAR", "code": "QA"},
	{"name": "REUNION", "code": "RE"},
	{"name": "ROMANIA", "code": "RO"},
	{"name": "RUSSIAN FEDERATION", "translation": "RUSSIA"},
	{"name": "MOSCOW", "translation": "RUSSIA"},
	{"name": "USSR", "translation": "RUSSIA"},
	{"name": "TASSR", "translation": "RUSSIA"},
	{"name": "KASSR", "translation": "RUSSIA"},
	{"name": "RUSSIA", "code": "RU"},
	{"name": "RWANDA", "code": "RW"},
	{"name": "SAINT HELENA", "code": "SH"},
	{"name": "SAINT KITTS AND NEVIS", "code": "KN"},
	{"name": "SAINT LUCIA", "code": "LC"},
	{"name": "SAINT PIERRE AND MIQUELON", "code": "PM"},
	{"name": "SAINT VINCENT AND THE GRENADINES", "code": "VC"},
	{"name": "SAMOA", "code": "WS"},
	{"name": "SAN MARINO", "code": "SM"},
	{"name": "SAO TOME AND PRINCIPE", "code": "ST"},
	{"name": "SAUDI ARABIA", "code": "SA"},
	{"name": "SENEGAL", "code": "SN"},
	{"name": "KOSOVO", "translation": "SERBIA"},
	{"name": "SERBIA", "code": "SRB"},
	{"name": "MONTENEGRO", "code": "ME"},
	{"name": "SEYCHELLES", "code": "SC"},
	{"name": "SIERRA LEONE", "code": "SL"},
	{"name": "SINGAPORE", "code": "SG"},
	{"name": "SLOVAKIA", "code": "SK"},
	{"name": "SLOVENIA", "code": "SI"},
	{"name": "SOLOMON ISLANDS", "code": "SB"},
	{"name": "SOMALIA", "code": "SO"},
	{"name": "SOUTH AFRICA", "code": "ZA"},
	{"name": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "code": "GS"},
	{"name": "SPAIN", "code": "ES"},
	{"name": "SRI LANKA", "code": "LK"},
	{"name": "SUDAN", "code": "SD"},
	{"name": "SURINAME", "code": "SR"},
	{"name": "SVALBARD AND JAN MAYEN", "code": "SJ"},
	{"name": "SWAZILAND", "code": "SZ"},
	{"name": "SWEDEN", "code": "SE"},
	{"name": "SWITZERLAND", "code": "CH"},
	{"name": "SCHWEIZ", "translation": "SWITZERLAND"},
	{"name": "SYRIAN ARAB REPUBLIC", "code": "SY"},
	{"name": "SYRIA", "translation": "SYRIAN ARAB REPUBLIC"},
	{"name": "TAIWAN, PROVINCE OF CHINA", "code": "TW"},
	{"name": "TAIWAN", "translation": "TAIWAN, PROVINCE OF CHINA"},
	{"name": "TAJIKISTAN", "code": "TJ"},
	{"name": "TAJIKSTAN", "translation": "TAJIKISTAN"},
	{"name": "TANZANIA, UNITED REPUBLIC OF", "code": "TZ"},
	{"name": "TANZANIA", "translation": "TANZANIA, UNITED REPUBLIC OF"},
	{"name": "THAILAND", "code": "TH"},
	{"name": "TIMOR-LESTE", "code": "TL"},
	{"name": "TOGO", "code": "TG"},
	{"name": "TOKELAU", "code": "TK"},
	{"name": "TONGA", "code": "TO"},
	{"name": "TRINIDAD AND TOBAGO", "code": "TT"},
	{"name": "TOBAGO", "translate": "TRINIDAD AND TOBAGO"},
	{"name": "TUNISIA", "code": "TN"},
	{"name": "TURKEY", "code": "TR"},
	{"name": "TURKMENISTAN", "code": "TM"},
	{"name": "TURKS AND CAICOS ISLANDS", "code": "TC"},
	{"name": "TUVALU", "code": "TV"},
	{"name": "UGANDA", "code": "UG"},
	{"name": "UKRAINE", "code": "UA"},
	{"name": "UKSSR", "translation": "UKRAINE"},
	{"name": "CRIMEA", "translation": "UKRAINE"},
	{"name": "UNITED ARAB EMIRATES", "code": "AE"},
	{"name": "U ARAB EMIRATES", "translation": "UNITED ARAB EMIRATES"},
	{"name": "UNITED KINGDOM", "code": "GB"},
	{"name": "ENGLAND", "code": "GB"},
	{"name": "WALES", "code": "GB"},
	{"name": "SCOTLAND"},
	{"name": "ALEXANDRIA,VA", "translation": "USA"},
	{"name": "AMADO,CA", "translation": "USA"},
	{"name": "STERLING HTS,MI", "translation": "USA"},
	{"name": "CRETE,NE", "translation": "USA"},
	{"name": "ROCKVILLE,MD", "translation": "USA"},
	{"name": "ALEXANDRIA,VA", "translation": "USA"},
	{"name": "HOPKINTON,MA", "translation": "USA"},
	{"name": "NORTHAMPTON,MA", "translation": "USA"},
	{"name": "BINGHAMTON,NY", "translation": "USA"},
	{"name": "MEMPHIS,TN", "translation": "USA"},
	{"name": "HAYS,KS", "translation": "USA"},
	{"name": "HEMPSTEAD,NY", "translation": "USA"},
	{"name": "SILVER SPRING,MD", "translation": "USA"},
	{"name": "WHIPPANY,NJ", "translation": "USA"},
	{"name": "GREENVILLE,SC", "translation": "USA"},
	{"name": "SEWANEE,TN", "translation": "USA"},
	{"name": "GREENBANK,WV", "translation": "USA"},
	{"name": "E HANOVER,NJ", "translation": "USA"},
	{"name": "TARRYTOWN,NY", "translation": "USA"},
	{"name": "DAYTON,OH", "translation": "USA"},
	{"name": "LEWISTON,ME", "translation": "USA"},
	{"name": "RICHLAND,WA", "translation": "USA"},
	{"name": "AMES,IA", "translation": "USA"},
	{"name": "FRAMINGHAM,MA", "translation": "USA"},
	{"name": "REDWOOD CITY,CA", "translation": "USA"},
	{"name": "FT WORTH,TX", "translation": "USA"},
	{"name": "SHREWSBURY,MA", "translation": "USA"},
	{"name": "DURHAM,NC", "translation": "USA"},
	{"name": "ANDOVER,MA", "translation": "USA"},
	{"name": "ARNOLD AFB,TN", "translation": "USA"},
	{"name": "EL SEGUNDO,CA", "translation": "USA"},
	{"name": "BRONX,NY", "translation": "USA"},
	{"name": "MONROE,NC", "translation": "USA"},
	{"name": "RADFORD,VA", "translation": "USA"},
	{"name": "PHOENIX,AZ", "translation": "USA"},
	{"name": "MANHASSET,NY", "translation": "USA"},
	{"name": "CARPINTERIA,CA", "translation": "USA"},
	{"name": "WATERTOWN,MA", "translation": "USA"},
	{"name": "LEXINGTON,KY", "translation": "USA"},
	{"name": "HERSHEY,PA", "translation": "USA"},
	{"name": "ALBANY,NY", "translation": "USA"},
	{"name": "W HAVEN,CT", "translation": "USA"},
	{"name": "TROY,MI", "translation": "USA"},
	{"name": "BURLINGTON,MA", "translation": "USA"},
	{"name": "FT DAVIS,TX", "translation": "USA"},
	{"name": "BRYN MAWR,PA", "translation": "USA"},
	{"name": "SUNNYVALE,CA", "translation": "USA"},
	{"name": "GETTYSBURG,PA", "translation": "USA"},
	{"name": "STURBRIDGE,MA", "translation": "USA"},
	{"name": "BOWLING GREEN,OH", "translation": "USA"},
	{"name": "FREDERICK,MD", "translation": "USA"},
	{"name": "RIDGEFIELD,CT", "translation": "USA"},
	{"name": "THE WOODLANDS,TX", "translation": "USA"},
	{"name": "LITTLETON,CO", "translation": "USA"},
	{"name": "SALT LAKE CITY,UT", "translation": "USA"},
	{"name": "MIAMI,FL", "translation": "USA"},
	{"name": "WHIPPLE,AZ", "translation": "USA"},
	{"name": "DAVIDSON,NC", "translation": "USA"},
	{"name": "ST PAUL,MN", "translation": "USA"},
	{"name": "CULVER CITY,CA", "translation": "USA"},
	{"name": "ANGWIN,CA", "translation": "USA"},
	{"name": "WEBSTER,NY", "translation": "USA"},
	{"name": "EXETER,NH", "translation": "USA"},
	{"name": "PENSACOLA,FL", "translation": "USA"},
	{"name": "ANNAPOLIS,MD", "translation": "USA"},
	{"name": "MORRIS PLAINS,NJ", "translation": "USA"},
	{"name": "E ORANGE,NJ", "translation": "USA"},
	{"name": "ESSEX JCT,VT", "translation": "USA"},
	{"name": "RES TRIANGLE PK,NC", "translation": "USA"},
	{"name": "TOLEDO,IL", "translation": "USA"},
	{"name": "HIRAM,OH", "translation": "USA"},
	{"name": "BEDFORD,MA", "translation": "USA"},
	{"name": "HONOLULU,HI", "translation": "USA"},
	{"name": "WALTHAM,MA", "translation": "USA"},
	{"name": "HENDERSON,NV", "translation": "USA"},
	{"name": "ALBUQUERQUE,NM", "translation": "USA"},
	{"name": "GRANVILLE,OH", "translation": "USA"},
	{"name": "NORTHFIELD,MN", "translation": "USA"},
	{"name": "LANCASTER,PA", "translation": "USA"},
	{"name": "HAMPTON,VA", "translation": "USA"},
	{"name": "WILLIAMSBURG,VA", "translation": "USA"},
	{"name": "GREENCASTLE,IN", "translation": "USA"},
	{"name": "SAN ANTONIO,TX", "translation": "USA"},
	{"name": "UPTON,NY", "translation": "USA"},
	{"name": "URBANA,IL", "translation": "USA"},
	{"name": "UNIV PK,PA", "translation": "USA"},
	{"name": "CHESTER,PA", "translation": "USA"},
	{"name": "FREMONT,CA", "translation": "USA"},
	{"name": "FOGLESVILLE,PA", "translation": "USA"},
	{"name": "DANBURY,CT", "translation": "USA"},
	{"name": "ST PETERSBURG,FL", "translation": "USA"},
	{"name": "MASON,OH", "translation": "USA"},
	{"name": "GOLETA,CA", "translation": "USA"},
	{"name": "ANAHEIM,CA", "translation": "USA"},
	{"name": "CARLSBAD,CA", "translation": "USA"},
	{"name": "MILILANI,HI", "translation": "USA"},
	{"name": "BETHESDA,MD", "translation": "USA"},
	{"name": "BROOKS AFB,TX", "translation": "USA"},
	{"name": "LEXINGTON,MA", "translation": "USA"},
	{"name": "OSWEGO,NY", "translation": "USA"},
	{"name": "OGDEN,UT", "translation": "USA"},
	{"name": "MANKATO,MN", "translation": "USA"},
	{"name": "BIG PINE,CA", "translation": "USA"},
	{"name": "MORAGA,CA", "translation": "USA"},
	{"name": "PATRICK AFB,FL", "translation": "USA"},
	{"name": "KIRTLAND AFB,NM", "translation": "USA"},
	{"name": "ELSAH,IL", "translation": "USA"},
	{"name": "DANVERS,MA", "translation": "USA"},
	{"name": "ANNAPOLIS JUNCTION,MD", "translation": "USA"},
	{"name": "KENNEDY SPACE CTR,FL", "translation": "USA"},
	{"name": "NEWTON,MA", "translation": "USA"},
	{"name": "OAK RIDGE,TN", "translation": "USA"},
	{"name": "WOODBURY,NY", "translation": "USA"},
	{"name": "SAN JUAN CAPISTRANO,CA", "translation": "USA"},
	{"name": "NACOGDOCHES,TX", "translation": "USA"},
	{"name": "NORFOLK,VA", "translation": "USA"},
	{"name": "DAHLGREN,VA", "translation": "USA"},
	{"name": "GOLDEN VALLEY,MN", "translation": "USA"},
	{"name": "TOLEDO,OH", "translation": "USA"},
	{"name": "WORCESTER,MA", "translation": "USA"},
	{"name": "HOLMDEL,NJ", "translation": "USA"},
	{"name": "SEVERNA PK,MD", "translation": "USA"},
	{"name": "REDONDO BEACH,CA", "translation": "USA"},
	{"name": "ROCKY FORD,CO", "translation": "USA"},
	{"name": "FAIRBORN,OH", "translation": "USA"},
	{"name": "SACRAMENTO,CA", "translation": "USA"},
	{"name": "ATCHISON,KS", "translation": "USA"},
	{"name": "RESTON,VA", "translation": "USA"},
	{"name": "JACKSON,MS", "translation": "USA"},
	{"name": "MEDFORD,MA", "translation": "USA"},
	{"name": "COLUMBUS,GA", "translation": "USA"},
	{"name": "TOMS RIVER,NJ", "translation": "USA"},
	{"name": "CASTLETON ON HUDSON,NY", "translation": "USA"},
	{"name": "SEATTLE,WA", "translation": "USA"},
	{"name": "NEW ORLEANS,LA", "translation": "USA"},
	{"name": "HILL,MA", "translation": "USA"},
	{"name": "COLUMBIA,SC", "translation": "USA"},
	{"name": "WILLIAMSTOWN,MA", "translation": "USA"},
	{"name": "MCLEAN,VA", "translation": "USA"},
	{"name": "OBERLIN,OH", "translation": "USA"},
	{"name": "DECATUR,IL", "translation": "USA"},
	{"name": "HAYWARD,CA", "translation": "USA"},
	{"name": "GAITHERSBURG,MD", "translation": "USA"},
	{"name": "NASHVILLE,TN", "translation": "USA"},
	{"name": "LAFAYETTE,IN", "translation": "USA"},
	{"name": "MIDDLEBURY,VT", "translation": "USA"},
	{"name": "MT VIEW,CA", "translation": "USA"},
	{"name": "MOFFETT FIELD,CA", "translation": "USA"},
	{"name": "DALLAS,TX", "translation": "USA"},
	{"name": "ARECIBO,PR", "translation": "USA"},
	{"name": "GENESEO,NY", "translation": "USA"},
	{"name": "SEABROOK,MD", "translation": "USA"},
	{"name": "MURRAY HILL,NJ", "translation": "USA"},
	{"name": "KAMUELA,HI", "translation": "USA"},
	{"name": "MURRAY,KY", "translation": "USA"},
	{"name": "LANDOVER,MD", "translation": "USA"},
	{"name": "EMPORIA,KS", "translation": "USA"},
	{"name": "OXFORD,GA", "translation": "USA"},
	{"name": "SYRACUSE,NY", "translation": "USA"},
	{"name": "DES MOINES,IA", "translation": "USA"},
	{"name": "FRIDAY HARBOR,WA", "translation": "USA"},
	{"name": "CHARLESTON,SC", "translation": "USA"},
	{"name": "FULLERTON,CA", "translation": "USA"},
	{"name": "PISCATAWAY,NJ", "translation": "USA"},
	{"name": "CINCINNATI,OH", "translation": "USA"},
	{"name": "SCOTTS VALLEY,CA", "translation": "USA"},
	{"name": "BOONE,NC", "translation": "USA"},
	{"name": "FAIRFAX,VA", "translation": "USA"},
	{"name": "STATE COLL,PA", "translation": "USA"},
	{"name": "WESTFORD,MA", "translation": "USA"},
	{"name": "MILFORD,MA", "translation": "USA"},
	{"name": "ARLINGTON,VA", "translation": "USA"},
	{"name": "LANHAM,MD", "translation": "USA"},
	{"name": "WINSTON SALEM,NC", "translation": "USA"},
	{"name": "LAUREL,MD", "translation": "USA"},
	{"name": "SALISBURY,MD", "translation": "USA"},
	{"name": "GLENDORA,CA", "translation": "USA"},
	{"name": "PROVIDENCE,RI", "translation": "USA"},
	{"name": "HAMPDEN SYDNEY,VA", "translation": "USA"},
	{"name": "BETHPAGE,NY", "translation": "USA"},
	{"name": "MADISON,NJ", "translation": "USA"},
	{"name": "ST CLOUD,MN", "translation": "USA"},
	{"name": "KENT,OH", "translation": "USA"},
	{"name": "OIL CITY,PA", "translation": "USA"},
	{"name": "SAN LEANDRO,CA", "translation": "USA"},
	{"name": "ROCHESTER,NY", "translation": "USA"},
	{"name": "ATLANTA,GA", "translation": "USA"},
	{"name": "COLUMBUS,OH", "translation": "USA"},
	{"name": "SANTA ANA HTS,CA", "translation": "USA"},
	{"name": "MEADVILLE,PA", "translation": "USA"},
	{"name": "ROANOKE,VA", "translation": "USA"},
	{"name": "CARLISLE,PA", "translation": "USA"},
	{"name": "SAN JOSE,CA", "translation": "USA"},
	{"name": "NANTUCKET,MA", "translation": "USA"},
	{"name": "PALO ALTO,CA", "translation": "USA"},
	{"name": "VIENNA,VA", "translation": "USA"},
	{"name": "BROOKLYN,NY", "translation": "USA"},
	{"name": "SOCORRO,NM", "translation": "USA"},
	{"name": "COLUMBIA,MD", "translation": "USA"},
	{"name": "BALTIMORE,MD", "translation": "USA"},
	{"name": "CLEMSON,SC", "translation": "USA"},
	{"name": "CLAREMONT,CA", "translation": "USA"},
	{"name": "BOSTON,MA", "translation": "USA"},
	{"name": "LONG BEACH,CA", "translation": "USA"},
	{"name": "HILO,HI", "translation": "USA"},
	{"name": "LAS CRUCES,NM", "translation": "USA"},
	{"name": "CLEVELAND,OH", "translation": "USA"},
	{"name": "ANNAPOLIS JCT,MD", "translation": "USA"},
	{"name": "POUGHKEEPSIE,NY", "translation": "USA"},
	{"name": "TROY,NY", "translation": "USA"},
	{"name": "VILLANOVA,PA", "translation": "USA"},
	{"name": "MOORHEAD,MN", "translation": "USA"},
	{"name": "STONY BROOK,NY", "translation": "USA"},
	{"name": "UNIVERSITY PK,PA", "translation": "USA"},
	{"name": "HANOVER,NH", "translation": "USA"},
	{"name": "SANTA BARBARA,CA", "translation": "USA"},
	{"name": "DAVIS,CA", "translation": "USA"},
	{"name": "HUNTSVILLE,AL", "translation": "USA"},
	{"name": "LIVERMORE,CA", "translation": "USA"},
	{"name": "BOULDER,CO", "translation": "USA"},
	{"name": "ARGONNE,IL", "translation": "USA"},
	{"name": "BATAVIA,IL", "translation": "USA"},
	{"name": "NEW HAVEN,CT", "translation": "USA"},
	{"name": "YORKTOWN HTS,NY", "translation": "USA"},
	{"name": "ITHACA,NY", "translation": "USA"},
	{"name": "IRVINE,CA", "translation": "USA"},
	{"name": "AMADO,AZ", "translation": "USA"},
	{"name": "EVANSTON,IL", "translation": "USA"},
	{"name": "RHODE ISL", "translation": "USA"},
	{"name": "SCHENECTADY,NY", "translation": "USA"},
	{"name": "KINGSTON,RI", "translation": "USA"},
	{"name": "LOS ALAMOS,NM", "translation": "USA"},
	{"name": "AMHERST,MA", "translation": "USA"},
	{"name": "HAVERFORD,PA", "translation": "USA"},
	{"name": "BELOIT,WI", "translation": "USA"},
	{"name": "HAMILTON,NY", "translation": "USA"},
	{"name": "BETHLEHEM,PA", "translation": "USA"},
	{"name": "SAN FRANCISCO,CA", "translation": "USA"},
	{"name": "MARINA DEL REY,CA", "translation": "USA"},
	{"name": "ROHNERT PK,CA", "translation": "USA"},
	{"name": "EUREKA,CA", "translation": "USA"},
	{"name": "HAMILTON,CA", "translation": "USA"},
	{"name": "STANFORD,CA", "translation": "USA"},
	{"name": "LA JOLLA,CA", "translation": "USA"},
	{"name": "CHARLOTTESVILLE,VA", "translation": "USA"},
	{"name": "AUSTIN,TX", "translation": "USA"},
	{"name": "POMONA,CA", "translation": "USA"},
	{"name": "PASADENA,CA", "translation": "USA"},
	{"name": "LOS ANGELES,CA", "translation": "USA"},
	{"name": "MADISON,WI", "translation": "USA"},
	{"name": "RIVERSIDE,CA", "translation": "USA"},
	{"name": "SANTA MONICA,CA", "translation": "USA"},
	{"name": "FLAGSTAFF,AZ", "translation": "USA"},
	{"name": "DENVER,CO", "translation": "USA"},
	{"name": "PRINCETON,NJ", "translation": "USA"},
	{"name": "NEW BRUNSWICK,NJ", "translation": "USA"},
	{"name": "PHILADELPHIA,PA", "translation": "USA"},
	{"name": "MIDDLETOWN,CT", "translation": "USA"},
	{"name": "BERKELEY,CA", "translation": "USA"},
	{"name": "PITTSBURGH,PA", "translation": "USA"},
	{"name": "SWARTHMORE,PA", "translation": "USA"},
	{"name": "HOUSTON,TX", "translation": "USA"},
	{"name": "SUNSPOT,NM", "translation": "USA"},
	{"name": "SANTA CRUZ,CA", "translation": "USA"},
	{"name": "CAMBRIDGE,MA", "translation": "USA"},
	{"name": "SAN DIEGO,CA", "translation": "USA"},
	{"name": "GREEN BANK,WV", "translation": "USA"},
	{"name": "UNITED STATES", "translation": "USA"},
	{"name": "GREENBELT,MD", "translation": "USA"},
	{"name": "USA", "code": "US"},
	{"name": "UNITED STATES MINOR OUTLYING ISLANDS", "code": "UM"},
	{"name": "URUGUAY", "code": "UY"},
	{"name": "UZSSR", "translation": "UZBEKISTAN"},
	{"name": "UZBEKISTAN", "code": "UZ"},
	{"name": "VANUATU", "code": "VU"},
	{"name": "VENEZUELA", "code": "VE"},
	{"name": "VIET NAM", "code": "VN"},
	{"name": "VIRGIN ISLANDS, BRITISH", "code": "VG"},
	{"name": "VIRGIN ISLANDS, U.S.", "code": "VI"},
	{"name": "WALLIS AND FUTUNA", "code": "WF"},
	{"name": "WESTERN SAHARA", "code": "EH"},
	{"name": "YEMEN", "code": "YE"},
	{"name": "ZAMBIA", "code": "ZM"},
	{"name": "ZIMBABWE", "code": "ZW"},
	{"name": "CHICAGO", "translation": "USA"},
	{"name": "ALABAMA", "translation": "USA"},
	{"name": "ALASKA", "translation": "USA"},
	{"name": "ARIZONA", "translation": "USA"},
	{"name": "ARKANSAS", "translation": "USA"},
	{"name": "CALIFORNIA", "translation": "USA"},
	{"name": "COLORADO", "translation": "USA"},
	{"name": "CONNECTICUT", "translation": "USA"},
	{"name": "DELAWARE", "translation": "USA"},
	{"name": "FLORIDA", "translation": "USA"},
	{"name": "GEORGIA", "translation": "USA"},
	{"name": "HAWAII", "translation": "USA"},
	{"name": "IDAHO", "translation": "USA"},
	{"name": "ILLINOIS", "translation": "USA"},
	{"name": "INDIANA", "translation": "USA"},
	{"name": "IOWA", "translation": "USA"},
	{"name": "KANSAS", "translation": "USA"},
	{"name": "KENTUCKY", "translation": "USA"},
	{"name": "LOUISIANA", "translation": "USA"},
	{"name": "MAINE", "translation": "USA"},
	{"name": "MARYLAND", "translation": "USA"},
	{"name": "MASSACHUSETTS", "translation": "USA"},
	{"name": "MICHIGAN", "translation": "USA"},
	{"name": "MINNESOTA", "translation": "USA"},
	{"name": "MISSISSIPPI", "translation": "USA"},
	{"name": "MISSOURI", "translation": "USA"},
	{"name": "MONTANA", "translation": "USA"},
	{"name": "NEBRASKA", "translation": "USA"},
	{"name": "NEVADA", "translation": "USA"},
	{"name": "NEW HAMPSHIRE", "translation": "USA"},
	{"name": "NEW JERSEY", "translation": "USA"},
	{"name": "NEW MEXICO", "translation": "USA"},
	{"name": "NEW YORK", "translation": "USA"},
	{"name": "CAROLINA", "translation": "USA"},
	{"name": "DAKOTA", "translation": "USA"},
	{"name": "OHIO", "translation": "USA"},
	{"name": "OKLAHOMA", "translation": "USA"},
	{"name": "OREGON", "translation": "USA"},
	{"name": "PENNSYLVANIA", "translation": "USA"},
	{"name": "RHODE ISLAND", "translation": "USA"},
	{"name": "SOUTH CAROLINA", "translation": "USA"},
	{"name": "SOUTH DAKOTA", "translation": "USA"},
	{"name": "TENNESSEE", "translation": "USA"},
	{"name": "TEXAS", "translation": "USA"},
	{"name": "UTAH", "translation": "USA"},
	{"name": "VERMONT", "translation": "USA"},
	{"name": "VIRGINIA", "translation": "USA"},
	{"name": "WASHINGTON", "translation": "USA"},
	{"name": "TUCSON", "translation": "USA"},
	{"name": "WEST VIRGINIA", "translation": "USA"},
	{"name": "WISCONSIN", "translation": "USA"},
	{"name": "WYOMING", "translation": "USA"},
	{"name": "NOTRE DAME", "translation": "FRANCE"},
]